# Copyright LLM.build Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

"""Generate a skeleton buildtest.yaml from an executable build.yaml (issue #278).

Kept import-light (only gbcommon + stdlib) so ``gbtest render`` does not pull the
heavy test-infra imports in ``buildtest.py`` before pytest sessionstart.
"""

from pathlib import Path
from typing import Any, Dict, List

from libgbtest.buildrunner.placeholder import PLACEHOLDER

from gbcommon.types.buildconfig import BuildConfig


def derive_expectations(build_yaml_path: Path) -> List[Dict[str, Any]]:
    """Per-target DERIVABLE expectations from a build.yaml.

    Only ``input_artifact_count`` / ``output_artifact_count`` are statically
    knowable (declared inputs/outputs). ``step_count`` and ``jobstats_count`` are
    NOT derivable and are left to ``generate_skeleton`` to emit as ``PLACEHOLDER``.
    """
    config = BuildConfig.from_yaml(path=Path(build_yaml_path))
    out: List[Dict[str, Any]] = []
    for name, target in config.targets.items():
        out.append(
            {
                "target_name": name,
                "input_artifact_count": len(target.inputs or {}),
                "output_artifact_count": len(target.outputs or {}),
            }
        )
    return out


def generate_skeleton(build_yaml_path: Path) -> str:
    """Return skeleton buildtest.yaml text; non-derivable ``step_count`` is ``PLACEHOLDER``."""
    exps = derive_expectations(build_yaml_path)
    lines = [
        "# Skeleton generated by `gbtest render`. Replace every FIXME before running.",
        "# step_count: set the observed count, or -1 to skip the step assertion.",
        "# jobstats_count: defaults to -1 (skip); jobstats are not asserted at run time yet.",
        "# output_artifact_count counts DECLARED outputs; a declared output whose command",
        "#   emits no LLMB_ARTIFACT marker will over-count (a real run catches it).",
        "build_yaml: ./build.yaml",
        "simulate_step_failure: false        # step-retry testing off",
        "tests: [runner]                     # cancellation test disabled",
        "timeout_minutes: 30",
        "targets:",
    ]
    lines += [f"  - {e['target_name']}" for e in exps]
    lines.append("target_expectations:")
    for e in exps:
        lines += [
            f"  - target_name: {e['target_name']}",
            f"    input_artifact_count: {e['input_artifact_count']}",
            f"    output_artifact_count: {e['output_artifact_count']}",
            f"    step_count: {PLACEHOLDER}        # FIXME: observed count, or -1 to skip",
            "    jobstats_count: -1               # not asserted at run time yet; -1 = skip",
        ]
    return "\n".join(lines) + "\n"
